### ISSUE TITLE
Exclude any addon that is outdated 

### ISSUE THREAD

**Issue by DakJaniels** [Garethp/Vortex-ESOUI#2]
There needs to be a way that when a user searches for an addon, it does not pull any addon from this category https://www.esoui.com/downloads/cat157.html

example. search for advanced filters.  A user will be more inclined to download 
https://www.esoui.com/downloads/info245-AdvancedFilters.html Because it shows it has more downloads than the current https://www.esoui.com/downloads/info2215-AdvancedFilters-Updated.html

then it just goes haywire from there because vortex installs the needed libraries and some of them can be from the discontinued and outdated section as well.

**Comment by dyoung522** [comment]
An easy workaround might be to simply show the "last updated date" in the search results
